"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's2et05_9$y1^xq7e37md5n1y4cb#vq48by_kfs=m559v_t)-ks'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
    'djcelery',
    'Buyer.templatetags',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'Qshop.middlewaretest.MiddleWareTest',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qshop',
        'USER':'root',
        'PASSWORD':'',
        'HOST':'127.0.0.1',
        'PORT':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static'),
)

# STATIC_ROOT=os.path.join(BASE_DIR,'static')

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static')

from alipay import AliPay
alipay_public_key_string="""-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzlV3HoHYrLXrzpsXCSMCZpWVR8CLYjv5Y84UHRu5yOC0l01RkWVem/vXRCYl0BumJ8ILot/F1Q4/u9Ed5nH3mWOdm+GAWAp10xl6eJjlwetO0KuLsSIVIvf+37YibgA8I2l2OSER2dV/KQg8Lqg827mc+66SxdpWIKDv0iu7POQ2D4qczBc5C2+xTuDSkgCX8FBwlrCbMlTswwlNSs/LMjiIYsBzS3Iw36u0TrJpc3dZesDz9TJMNmHtiwJaBCiW3mkrlyIaMQwJQEalhyNc3kGNaRMgDmG0SUyJ058GLbFOQlRmZ3xvWHavNdrYELA6uIfmCp+ZCj09gumksM/HvQIDAQAB
-----END PUBLIC KEY-----"""
app_private_key_string ="""-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAzlV3HoHYrLXrzpsXCSMCZpWVR8CLYjv5Y84UHRu5yOC0l01RkWVem/vXRCYl0BumJ8ILot/F1Q4/u9Ed5nH3mWOdm+GAWAp10xl6eJjlwetO0KuLsSIVIvf+37YibgA8I2l2OSER2dV/KQg8Lqg827mc+66SxdpWIKDv0iu7POQ2D4qczBc5C2+xTuDSkgCX8FBwlrCbMlTswwlNSs/LMjiIYsBzS3Iw36u0TrJpc3dZesDz9TJMNmHtiwJaBCiW3mkrlyIaMQwJQEalhyNc3kGNaRMgDmG0SUyJ058GLbFOQlRmZ3xvWHavNdrYELA6uIfmCp+ZCj09gumksM/HvQIDAQABAoIBAQC2EPoUZFUySTCzVWylNkw3AwT/lGopm2w7YiujZ8Su+YDBBYvVNVKfZ0ETNGonUU5zRKmJ5dUmY/VfIG422xe1NQ5s7zWV+lzvkkrcQWZzj9QzEzwnaECoY5Z2BrwovnJSeQvF62VaBya2qTqZnQBejlF0UB3ZEgjvr7MOjGIinlMOqPr+avp/zOlSVD2lYO0lil5Uz46zkeSEqQoP5cRwF/M6OsI7LIdX84IrmWQD/RifW1//Rh3t3lD3ZOrMxT7PHKfb/t2sfQ72YY2KXsFiFqyM/7TwXeXv8nJLmuyLgFc1NwDJZEwFblFYUiL5g5Xjy8S7cp8WWbBIMhKZ4WxBAoGBAO/3DLIrwCBhvjKwLbHWftlVfGFOM9ci9fHqekoqaIdbwvK0qOeYdfItvqARmhhh3gIdF2pHeFkwWCtqSDiDfFoETjjMKMrp4f+tLjuCTd9BDDqVWIFjITEQq5yHfLaQGfEMPNHa+OsP+77ly2uSvidbw0A38nRNNKwkmqe/1P/xAoGBANwfGvuEdKVZVd8lbaGFGAwAblcZXBNlu1CJ0N3/uIJnJ0f/OizECeG4Zhc7EKRpSRIuXssb40ywe9xoKL5bIOeVvm6RqSU5z0Iu4fJTgatiSWfCNfg8qmxqL3mFm1X5nxcZ1IgBgYpgK9Pby7/TDt21E4yrLbAXV5NLace8O9CNAoGBAM9d1JDbkenpzW0MJlC6JWA2qYeFBvNw+MyXbhpNT4s5VtxaFmQcskAYG9VDoMBVQn7dGPD01iFsz6Sk8cg0h+9aLSaT9uRy/KPvyjYOwrCdC65MhPE68uHtn/9ibfltyZ0ukBhhfB3V8Bzlg8ZwRvbIK5CBSHoMheoEr8kq0yxhAoGANooGd3c0J5vg6O8vIKwHb0HUFQSVicDVDnl3JOotXzILy4zzbxALmr/Dm9Hop7PmhPi0SALa6K95oPy1y6RsnLS/gEna7PxL3Awds5r5L+ukYG8ATEdLupz8slFmUYEN5/1gaWpmHFEDyvRUoWy77DbnZx0qrsy5yCcRSIndECkCgYEAnCkwvFtXVO2pbhMaG8OuIa/B+q98v468uUZdBepaNvlHoIqhvz+/l8OeFfkCZqsfJOXoZaqkMfYCaDyISpqfg2F0z4UEsFVEv0J7MWFgSqUtUnTzNk8LU6YOqpZK2zDlGrhZ92ewX+v7VLLcyGX2Y1rc0yWWDBwfNI10+vdO0vg=
-----END RSA PRIVATE KEY-----"""

appid="2016101600701596"

alipay=AliPay(
    appid=appid,
    app_notify_url=None,
    app_private_key_string=app_private_key_string,
    alipay_public_key_string=alipay_public_key_string,
    sign_type="RSA2",
    debug=False
)


import djcelery  ## 导包
djcelery.setup_loader()  ## 模块加载
BROKER_URL = 'redis://127.0.0.1:6379/1'    ### 中间人  消息中间件 指定连接redis中的第二个库作为消息队列
CELERY_IMPORTS = ('CeleryTask.tasks')  ##具体的任务文件
CELERY_TIMEZONE = 'Asia/Shanghai'   ## celery 时区
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"  ### celery的处理器 固定的

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION':['127.0.0.1:11211']
    }
}
CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 600
CACHE_MIDDLEWARE_ALIAS = 'default'